import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'About us',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <h2>About us</h2>
      <ul>
        <li><Link href="/about/team">Team</Link></li>
        <li><Link href="/about/contacts">Contacts</Link></li>
      </ul>
      {children}
    </div>
  )
}
